### Логистическая регрессия

1. Загрузите данные `load_wine` из `sklearn.datasets`. Из данных исключите объекты класса 2.
 Отмасштабируйте признаки, используя класс `StandardScaler` с гиперпараметрами по умолчанию. Обучите логистическую регрессию и оцените важность признаков. Укажите название признака, который оказался наименее значимым.

Обратите внимание, целевое значение лежит по ключу `'target'`, матрица объекты-признаки лежит по ключу `'data'`



In [11]:
from sklearn.datasets import load_wine
wine = load_wine()
print(len(wine['data']))

178


In [2]:
import numpy as np
import pandas as pd

In [12]:
df = pd.DataFrame(data =  np.c_[wine['data'], wine['target']],
                     columns  = wine['feature_names'] + ['target'])
print(df.shape)
df.head()

Result+Table:(178, 14)


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0     0.0  
1                          3.40   1050.0     0.0  
2                          3.17   1185.0     0.0  
3                          3.45   1480.0     0.0  
4                          2.93    735.0     0.0

In [13]:
bl = 2df = df.drop(df[df['target'] == bl].index)
print(df.shape)

Result:(130, 14)


In [23]:
from sklearn.preprocessing import StandardScaler

df1 = df.drop(['target'], axis=1)

scaler = StandardScaler()
scaler.fit(df1)
scalled_data = scaler.transform(df1)


Result+Table: (130, 13)


alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
0  1.452455   -0.294414  0.302478          -0.940375   1.768686   
1  0.289066   -0.214558 -0.677197          -2.239324   0.006527   
2  0.243886    0.447106  1.113242          -0.054728   0.071792   
3  1.610586   -0.020622  0.538951          -0.586117   0.854974   
4  0.334246    0.709490  1.788880           0.653789   1.181300   

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0       0.510421    0.775592             -0.462247         1.000229   
1       0.234327    0.367386             -0.646296        -0.878867   
2       0.510421    1.020516             -0.278198         1.967684   
3       2.443085    1.360688             -0.830346         0.795575   
4       0.510421    0.272138              0.550024         0.125798   

   color_intensity       hue  od280/od315_of_diluted_wines   proline  target  
0         0.892384 -0.112428                      2.040025  0.782868     0.0  
1         0.114374 -0.052918                      0.941437  0.740152     0.0  
2         0.917082 -0.171937                      0.455524  1.124598     0.0  
3         2.226115 -1.183603                      1.047071  1.964684     0.0  
4         0.077326 -0.112428                     -0.051517 -0.156889     0.0

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

X = scalled_data
y = df['target']

estimator = LogisticRegression()
selector = RFE(estimator, len(wine['feature_names'])-1, step=1)
selector = selector.fit(X, y)
selector.support_


array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True])

In [33]:
print(df1.columns)

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')


2. Загрузите данные `load_wine` из `sklearn.datasets`. Из обучающей части исключите объекты соответствующие классу 2. Не масштабируйте признаки. Обучите логистическую регрессию с гиперпараметрами по умолчанию.
Выберите признак из предложенных, которому соответствует минимальный вес. 


In [32]:
X = df1
y = df['target']

estimator = LogisticRegression()
selector = RFE(estimator, len(wine['feature_names'])-1, step=1)
selector = selector.fit(X, y)
selector.support_

d:\files\pycharm\machinelearningbasics\venv\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
d:\files\pycharm\machinelearningbasics\venv\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False])

3. Решается задача бинарной классификации. Дана матрица объекты признаки 𝑋 и ответы для объектов  𝑦. Обучите логистическую регрессию и предскажите класс объекта x_new

In [35]:
X = np.array([[1, 1], [0.3, 0.7], [0, 4], [-2, -7], [0, -2], [-1, -1], [-2, 0]])
y = np.array([1, 1, 1, 0, 0, 0])
x_new = np.array([[-5, 1]])

In [76]:
log_reg = LogisticRegression()
log_reg.fit(X[1:], y)
log_reg.predict(x_new)

array([0])

### Классификация текстов

4. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся 1572 объекта. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. Укажите полученное число признаков.


Чтобы загрузить данные, скачайте файл по ссылке. Если вы используете google colab, то пример загрузки данных приведен ниже.

In [68]:
spam_df = pd.read_csv("SMSSpamCollection",sep='\t', names=['target', 'text'])
spam_df.head()

train_df = spam_df[:4000]
test_df = spam_df[4000:]
print(len(train_df), len(test_df))

Result: 4000 1572


In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [71]:
vectorizer = TfidfVectorizer()
t = vectorizer.fit_transform(train_df['text'])
t.shape

Result: (4000, 7331)

5.  Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся 1572 объекта. Обучите `TfidfVectorizer`, помимо слов входящих в тексты, учитывайте биграммы (используйте гиперпараметр `ngram_range`). Укажите полученное число признаков.

In [90]:
vectorizer = TfidfVectorizer(ngram_range=[1,2])
t = vectorizer.fit_transform(train_df['text'])
t.shape

Result: (4000, 39805)

6. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся 1572 объекта. Обучите `TfidfVectorizer`, не учитывайте слова, которые встретились меньше 2 раз в обучающей выборке (используйте гиперпараметр `min_df`). Укажите полученное число признаков.

In [77]:
vectorizer = TfidfVectorizer(min_df=2)
t = vectorizer.fit_transform(train_df['text'])
t.shape

Result: (4000, 3377)

7. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся 1572 объекта. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. На полученных векторных представлениях обучите логистическую регрессию и оцените долю правильных ответов на тестовой части. Укажите полученное значение доли правильных ответов.

In [89]:
from sklearn.metrics import accuracy_score

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(train_df['text'])
X_test = vectorizer.transform(test_df['text'])

logreg = LogisticRegression()
logreg.fit(X_train, train_df['target'])

accuracy_score(test_df['target'], logreg.predict(X_test))

Result: 0.9694656488549618~0.96